In [1]:
import numpy as np

In [2]:
np.ndarray((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.29061074e-306]])

In [3]:
array_int=np.array([1,2,3])
array_int

array([1, 2, 3])

In [4]:
#two dimensional array
array_int2=np.array([[1,2,3],[2,3,4]])
array_int2

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
np.array(([1,2],[3,4]))

array([[1, 2],
       [3, 4]])

In [6]:
array_float=np.array(([1,2,3],[5,6.7,3]),dtype=float)
array_float

array([[1. , 2. , 3. ],
       [5. , 6.7, 3. ]])

In [7]:
array_float.dtype

dtype('float64')

In [8]:
type(array_float)

numpy.ndarray

### Changing data type of array
- Specifying during creation
- Type casting via .astype

In [9]:
array_int.astype('int8')


array([1, 2, 3], dtype=int8)

In [10]:
array_int.dtype

dtype('int32')

In [11]:
array_int_8=array_int.astype('int8')
array_int_8.dtype

dtype('int8')

In [12]:
new_arr=np.array([1,4,7],dtype=np.int8)
new_arr.dtype

dtype('int8')

### Data layout
- **itemsize** :specifies how many bytes are used for the data type
- **Stride**: specifies how many bytes we have to jump  in order to move to the next elementt

In [13]:
print(f"""Int1D itemsize: {array_int.itemsize}
Int1D strides: {array_int.strides}
Float2D itemsize: {array_float.itemsize}
Float2D strides: {array_float.strides}
    """)

Int1D itemsize: 4
Int1D strides: (4,)
Float2D itemsize: 8
Float2D strides: (24, 8)
    


In [14]:
arr = np.arange(9).reshape(3, 3)

print(arr)
print(f'The data type of each element is: {arr.dtype}')
print(f'The length of each element in bytes is: {arr.itemsize}')
print(f'The strides of the data types is: {arr.strides}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The data type of each element is: int32
The length of each element in bytes is: 4
The strides of the data types is: (12, 4)


### Transpose

In [15]:
transposed = arr.T

print(transposed)
transposed.strides

[[0 3 6]
 [1 4 7]
 [2 5 8]]


(4, 12)

In [16]:
ones = np.ones((3, 2)) # 2D matrix filled with ones
zeros = np.zeros_like(ones) # 2D zero matrix filled with zeros of the same shape as ones and zeros
identity = np.eye(3)

print(ones)
print(f'Shape of "one" is: {ones.shape}')
print(zeros)
print(f'Shape of "zeros" is: {zeros.shape}')
print(identity)
print(f'Shape of "identity" is: {identity.shape}')


[[1. 1.]
 [1. 1.]
 [1. 1.]]
Shape of "one" is: (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Shape of "zeros" is: (3, 2)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of "identity" is: (3, 3)


### Random array

In [17]:
vals = np.random.standard_normal(10)

vals

array([-1.54964176, -2.91089353, -1.80995271,  1.40480066,  0.6281781 ,
       -1.14965656,  0.19235534, -0.95833308,  1.4633789 ,  2.41270929])

In [18]:
# Random NORMAL distribution (mean: 0 and stddev: 1)
vals = np.random.randn(3, 4)

vals

array([[-0.19878801,  1.4833356 , -0.7489924 , -0.70079213],
       [-2.02439715, -0.92804164,  0.1015263 ,  0.34534607],
       [-2.97774182, -0.84911641,  0.7913057 ,  1.19647559]])

In [19]:
# Random UNIFORM distribution (0, 1 range)
vals = np.random.rand(3, 4)

vals

array([[0.05911425, 0.35757277, 0.98153333, 0.83370699],
       [0.74842887, 0.7040697 , 0.58344621, 0.81168653],
       [0.86672739, 0.84376627, 0.69655236, 0.07016121]])

In [20]:
array=np.array([1,2,3,4,5])
array[4]

5

In [21]:
np.random.randint(0,10,(3,4))

array([[5, 6, 3, 3],
       [5, 0, 6, 4],
       [6, 2, 9, 8]])

### Array operations
- Addition
- subtraction
- 
multiplicatio
- 
bitwise operations (whethe n array is boolean)

In [22]:
arr1=np.full((3,3),fill_value=5)
arr1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
identity_1=np.eye(arr1.shape[0],dtype='int64')
identity_1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [24]:
print(arr1)
print('    +    ')
print(identity_1)
print('    =    ')
print(arr1 + identity_1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
    +    
[[1 0 0]
 [0 1 0]
 [0 0 1]]
    =    
[[6 5 5]
 [5 6 5]
 [5 5 6]]


In [25]:
(np.cos(arr1) - np.sin(arr1) ** 3) / (np.eye(arr1.shape[0]) * np.e + 0.1)

array([[ 0.41352406, 11.65427351, 11.65427351],
       [11.65427351,  0.41352406, 11.65427351],
       [11.65427351, 11.65427351,  0.41352406]])

In [26]:
matrix = np.arange(20).reshape(5, 4)

matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
matrix[0, 0], matrix[1, 0], matrix[0, 1], matrix[2][0]

(0, 4, 1, 8)

In [28]:
matrix[0]

array([0, 1, 2, 3])

In [29]:
# : means all elements
# 0 means 0th column
matrix[:,0]

array([ 0,  4,  8, 12, 16])

In [30]:
matrix[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
matrix[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [32]:
matrix[0:3,0]

array([0, 4, 8])

In [33]:
# Inverse of columns

matrix[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16]])

In [34]:
matrix[::-1, ::-1]

array([[19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [35]:
matrix[::-3, ::-2]

array([[19, 17],
       [ 7,  5]])

In [36]:
# change to 3D tensor
temp = matrix.reshape(2, 2, -1)
temp.shape

(2, 2, 5)

In [37]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
# Column 0 and 2
matrix[:, [0, 2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
matrix[[-1, -1]]

array([[16, 17, 18, 19],
       [16, 17, 18, 19]])

In [40]:
#Shuffle rows using indices
indices=np.arange(matrix.shape[0])
indices

array([0, 1, 2, 3, 4])

In [41]:
permuted=np.random.permutation(indices)
permuted

array([3, 0, 2, 4, 1])

In [42]:
matrix[permuted]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [ 4,  5,  6,  7]])

In [43]:
# Obtaining only elements which fulfill condition
# In this case elements larger than 5

print(matrix > 5)

# Array has to be flat as it lost it's N x N structure
matrix[matrix > 5]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
my_array=np.random.rand(6,10)

In [45]:
my_array

array([[0.80691375, 0.83326643, 0.05358108, 0.53786891, 0.59674971,
        0.58382922, 0.95140066, 0.31309265, 0.03272954, 0.20705823],
       [0.20828871, 0.71933984, 0.47963457, 0.65489948, 0.64455941,
        0.56329906, 0.42912034, 0.97375636, 0.13279558, 0.43097206],
       [0.19151203, 0.07501112, 0.83938256, 0.60306057, 0.27216205,
        0.67610106, 0.55104076, 0.28613151, 0.33323928, 0.56171365],
       [0.7465106 , 0.10561345, 0.93975071, 0.32197218, 0.86086539,
        0.52135755, 0.7297788 , 0.94017741, 0.12554834, 0.09951953],
       [0.25997974, 0.57888491, 0.68914349, 0.62820506, 0.6077229 ,
        0.24131558, 0.81674636, 0.77387603, 0.62855211, 0.51700147],
       [0.50948761, 0.713149  , 0.73617291, 0.46224251, 0.81665283,
        0.04290385, 0.47922384, 0.67623025, 0.83389584, 0.10467007]])

In [46]:
new_array=my_array

In [47]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
a[1,2]

6

In [49]:
a[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
my_array

array([[0.80691375, 0.83326643, 0.05358108, 0.53786891, 0.59674971,
        0.58382922, 0.95140066, 0.31309265, 0.03272954, 0.20705823],
       [0.20828871, 0.71933984, 0.47963457, 0.65489948, 0.64455941,
        0.56329906, 0.42912034, 0.97375636, 0.13279558, 0.43097206],
       [0.19151203, 0.07501112, 0.83938256, 0.60306057, 0.27216205,
        0.67610106, 0.55104076, 0.28613151, 0.33323928, 0.56171365],
       [0.7465106 , 0.10561345, 0.93975071, 0.32197218, 0.86086539,
        0.52135755, 0.7297788 , 0.94017741, 0.12554834, 0.09951953],
       [0.25997974, 0.57888491, 0.68914349, 0.62820506, 0.6077229 ,
        0.24131558, 0.81674636, 0.77387603, 0.62855211, 0.51700147],
       [0.50948761, 0.713149  , 0.73617291, 0.46224251, 0.81665283,
        0.04290385, 0.47922384, 0.67623025, 0.83389584, 0.10467007]])

In [51]:
new_array=my_array[:,[1,3,5]]
new_array

array([[0.83326643, 0.53786891, 0.58382922],
       [0.71933984, 0.65489948, 0.56329906],
       [0.07501112, 0.60306057, 0.67610106],
       [0.10561345, 0.32197218, 0.52135755],
       [0.57888491, 0.62820506, 0.24131558],
       [0.713149  , 0.46224251, 0.04290385]])

In [52]:
my_array.shape

(6, 10)

In [53]:
new_array.shape

(6, 3)

In [54]:
my_array*new_array

ValueError: operands could not be broadcast together with shapes (6,10) (6,3) 

In [ ]:
new_array=new_array.T
new_array.shape

In [ ]:
arr = np.arange(18)
print(arr)

print(arr.shape, arr.strides)

In [ ]:

reshaped = arr.reshape(3, 2, -1)

In [ ]:
reshaped

In [ ]:
reshaped.shape

In [ ]:
arr = np.arange(18)

print(arr.shape, arr.strides)

reshaped = arr.reshape(3, 2, -1)

print(reshaped.shape, reshaped.strides)

print(f"Sharing underlying memory: {np.may_share_memory(arr, reshaped)}")

In [ ]:
arr[7] = 99999.

print(arr)
print(reshaped)