### Numpy
- Numpy is a Python library that helps create a multi-dimensional array and performs mathematical operations on arrays.

#### Installing NumPy
* conda install numpy 

* pip install numpy

In [69]:
#import numpy
import numpy as np

#### Array creation

In [70]:
my_list=[1,2,3,4,6]

In [71]:
arr=np.array(my_list)

In [72]:
arr

array([1, 2, 3, 4, 6])

In [73]:
type(arr)

numpy.ndarray

In [74]:
arr2=np.array([1.3,2.9,4.5])

In [75]:
arr2


array([1.3, 2.9, 4.5])

In [76]:
type(arr2)

numpy.ndarray

In [77]:
#type of the data
arr2.dtype

dtype('float64')

In [78]:
#multi dimensional array
list1=['Appple', 'Oranges']
list2=[1,2]
list3=['a', 'b']


In [79]:
arr=np.array([list1,list2,list3])

In [80]:
arr

array([['Appple', 'Oranges'],
       ['1', '2'],
       ['a', 'b']], dtype='<U11')

In [81]:
arr.ndim

2

In [82]:
type(arr)

numpy.ndarray

In [83]:
arr.shape

(3, 2)

### arange
- create arrays with regular interval values

In [84]:
#arrange given evenly spaced values within a given interval  
array1=np.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

In [85]:
type(array1)

numpy.ndarray

In [86]:
array1.dtype

dtype('int32')

In [87]:
#check the shape of the array
array1.shape

(6,)

In [88]:
array1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
array1.size

6

In [90]:
a=np.arange(15).reshape(3,5)

In [91]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
a.itemsize

4

In [102]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### linspace
- Return evenly spaced numbers over a specified interval.

In [98]:

np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [103]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### special case matrices
#### identity matrix

In [105]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [106]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
np.diag([1,4,7])

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 7]])

In [113]:
np.diag([1,4,7],2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Block matrix


In [139]:
A=np.zeros((2,2))
B=np.diag((3,4))
C=np.ones((2,2))
D=np.eye(2,2)

In [140]:
np.block([[A,B],[C,D]])

array([[0., 0., 3., 0.],
       [0., 0., 0., 4.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.]])

### random
- Create array with random number between zero to one

In [123]:
np.random.rand(3,5)

array([[0.23102405, 0.3653764 , 0.42360146, 0.07046339, 0.15452769],
       [0.45116771, 0.41416937, 0.06074462, 0.00919322, 0.96146207],
       [0.55489032, 0.62275908, 0.30506361, 0.47017766, 0.23698849]])

In [189]:
np.random.randn(2,4)

array([[ 0.28557471,  0.9865283 , -0.20162066,  1.94186492],
       [ 0.66602505,  0.69892639, -0.36921876, -1.99488199]])

In [194]:
np.random.randint(0,100,10).reshape(2,5)

array([[65, 21, 71, 33, 23],
       [86, 94, 53, 12, 13]])

In [196]:
np.random.random_sample((2,8))

array([[0.60239182, 0.10076992, 0.04472403, 0.04702647, 0.93520703,
        0.9184103 , 0.47998362, 0.83358941],
       [0.60974926, 0.35172716, 0.41336287, 0.41313336, 0.44401971,
        0.12277515, 0.6559921 , 0.36993309]])

## indexing

In [141]:
x=np.arange(10)

In [142]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
x[2]

2

In [154]:
y=x.reshape(2,5)

In [155]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [156]:
y[1,3]

8

In [157]:
y[1]

array([5, 6, 7, 8, 9])

In [158]:
y[0][2]

2

### slicing
- notation

start: stop:step

In [166]:
a=np.array([1,3,2,4,6,7,9,10])
a

array([ 1,  3,  2,  4,  6,  7,  9, 10])

In [167]:
a[1:6:2] #step2

array([3, 4, 7])

In [170]:
a[-2:7]

array([9])

In [160]:
z=np.arange(15).reshape(3,5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
z[2:3]

array([[10, 11, 12, 13, 14]])

In [171]:
z[1:,:3]

array([[ 5,  6,  7],
       [10, 11, 12]])

In [172]:
z[1:,-1]

array([ 9, 14])

In [173]:
z[:,1:-1]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [174]:
z[2:]=100
z

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [100, 100, 100, 100, 100]])

In [185]:
q=[1,2,3,4,5]
q=np.array(q)

In [187]:
q[1:]=100
q

array([  1, 100, 100, 100, 100])

In [188]:
z[z<3]

array([0, 1, 2])