In [1]:
import numpy as np

In [4]:
np.ndarray((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 6.95250701e-310]])

In [5]:
array_int=np.array([1,2,3])
array_int

array([1, 2, 3])

In [6]:
#two dimensional array
array_int2=np.array([[1,2,3],[2,3,4]])
array_int2

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
np.array(([1,2],[3,4]))

array([[1, 2],
       [3, 4]])

In [9]:
array_float=np.array(([1,2,3],[5,6.7,3]),dtype=float)
array_float

array([[1. , 2. , 3. ],
       [5. , 6.7, 3. ]])

In [11]:
array_float.dtype

dtype('float64')

In [12]:
type(array_float)

numpy.ndarray

### Changing data type of array
- Specifying during creation
- Type casting via .astype

In [14]:
array_int.astype('int8')


array([1, 2, 3], dtype=int8)

In [15]:
array_int.dtype

dtype('int32')

In [18]:
array_int_8=array_int.astype('int8')
array_int_8.dtype

dtype('int8')

In [19]:
new_arr=np.array([1,4,7],dtype=np.int8)
new_arr.dtype

dtype('int8')

### Data layout
- **itemsize** :specifies how many bytes are used for the data type
- **Stride**: specifies how many bytes we have to jump  in order to move to the next elementt

In [21]:
print(f"""Int1D itemsize: {array_int.itemsize}
Int1D strides: {array_int.strides}
Float2D itemsize: {array_float.itemsize}
Float2D strides: {array_float.strides}
    """)

Int1D itemsize: 4
Int1D strides: (4,)
Float2D itemsize: 8
Float2D strides: (24, 8)
    


In [22]:
arr = np.arange(9).reshape(3, 3)

print(arr)
print(f'The data type of each element is: {arr.dtype}')
print(f'The length of each element in bytes is: {arr.itemsize}')
print(f'The strides of the data types is: {arr.strides}')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The data type of each element is: int32
The length of each element in bytes is: 4
The strides of the data types is: (12, 4)


### Transpose

In [23]:
transposed = arr.T

print(transposed)
transposed.strides

[[0 3 6]
 [1 4 7]
 [2 5 8]]


(4, 12)

In [24]:
ones = np.ones((3, 2)) # 2D matrix filled with ones
zeros = np.zeros_like(ones) # 2D zero matrix filled with zeros of the same shape as ones and zeros
identity = np.eye(3)

print(ones)
print(f'Shape of "one" is: {ones.shape}')
print(zeros)
print(f'Shape of "zeros" is: {zeros.shape}')
print(identity)
print(f'Shape of "identity" is: {identity.shape}')


[[1. 1.]
 [1. 1.]
 [1. 1.]]
Shape of "one" is: (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Shape of "zeros" is: (3, 2)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of "identity" is: (3, 3)


### Random array

In [25]:
vals = np.random.standard_normal(10)

vals

array([ 1.36065425,  2.06251716,  2.34511838,  0.12289844,  0.11021055,
       -1.05321954, -1.37502257,  0.90263963, -0.32273629,  0.78989444])

In [26]:
# Random NORMAL distribution (mean: 0 and stddev: 1)
vals = np.random.randn(3, 4)

vals

array([[-0.98040455, -0.9945083 ,  0.95710779, -0.04241979],
       [-0.77885693,  0.70424148, -1.76889281, -0.76916917],
       [-2.1209549 , -0.75808833, -1.24306337, -0.22036339]])

In [27]:
# Random UNIFORM distribution (0, 1 range)
vals = np.random.rand(3, 4)

vals

array([[0.61876318, 0.52713605, 0.60381254, 0.98502776],
       [0.43165827, 0.7751283 , 0.63651772, 0.07399893],
       [0.11822637, 0.38904977, 0.43289062, 0.66423085]])

In [29]:
array=np.array([1,2,3,4,5])
array[4]

5

In [30]:
np.random.randint(0,10,(3,4))

array([[6, 6, 4, 3],
       [9, 8, 2, 3],
       [4, 4, 7, 8]])

### Array operations
- Addition
- subtraction
- 
multiplicatio
- 
bitwise operations (whethe n array is boolean)

In [31]:
arr1=np.full((3,3),fill_value=5)
arr1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
identity_1=np.eye(arr1.shape[0],dtype='int64')
identity_1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [34]:
print(arr1)
print('    +    ')
print(identity_1)
print('    =    ')
print(arr1 + identity_1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
    +    
[[1 0 0]
 [0 1 0]
 [0 0 1]]
    =    
[[6 5 5]
 [5 6 5]
 [5 5 6]]


In [35]:
(np.cos(arr1) - np.sin(arr1) ** 3) / (np.eye(arr1.shape[0]) * np.e + 0.1)

array([[ 0.41352406, 11.65427351, 11.65427351],
       [11.65427351,  0.41352406, 11.65427351],
       [11.65427351, 11.65427351,  0.41352406]])

In [36]:
matrix = np.arange(20).reshape(5, 4)

matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
matrix[0, 0], matrix[1, 0], matrix[0, 1], matrix[2][0]

(0, 4, 1, 8)

In [38]:
matrix[0]

array([0, 1, 2, 3])

In [40]:
# : means all elements
# 0 means 0th column
matrix[:,0]

array([ 0,  4,  8, 12, 16])

In [41]:
matrix[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
matrix[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [45]:
matrix[0:3,0]

array([0, 4, 8])

In [46]:
# Inverse of columns

matrix[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16]])

In [47]:
matrix[::-1, ::-1]

array([[19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [48]:
matrix[::-3, ::-2]

array([[19, 17],
       [ 7,  5]])

In [49]:
# change to 3D tensor
temp = matrix.reshape(2, 2, -1)
temp.shape

(2, 2, 5)

In [50]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [51]:
# Column 0 and 2
matrix[:, [0, 2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [52]:
matrix[[-1, -1]]

array([[16, 17, 18, 19],
       [16, 17, 18, 19]])

In [55]:
#Shuffle rows using indices
indices=np.arange(matrix.shape[0])
indices

array([0, 1, 2, 3, 4])

In [56]:
permuted=np.random.permutation(indices)
permuted

array([2, 4, 3, 0, 1])

In [57]:
matrix[permuted]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [58]:
# Obtaining only elements which fulfill condition
# In this case elements larger than 5

print(matrix > 5)

# Array has to be flat as it lost it's N x N structure
matrix[matrix > 5]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
my_array=np.random.rand(6,10)

In [60]:
my_array

array([[0.78138219, 0.47664021, 0.98952576, 0.78586048, 0.12498951,
        0.52931984, 0.09080556, 0.19903083, 0.14662074, 0.87930409],
       [0.12401796, 0.89570802, 0.62164808, 0.84320727, 0.84553637,
        0.38317026, 0.2838284 , 0.05423121, 0.19489253, 0.88175782],
       [0.9320304 , 0.26021669, 0.80479284, 0.76822814, 0.10175907,
        0.7729878 , 0.46601094, 0.97447559, 0.84678637, 0.52428617],
       [0.97781464, 0.70358998, 0.17628645, 0.84710726, 0.45328381,
        0.0606557 , 0.75937481, 0.78560602, 0.41007636, 0.31935431],
       [0.36857247, 0.62932669, 0.72415787, 0.98945275, 0.1729777 ,
        0.30101468, 0.59740391, 0.87682127, 0.5987741 , 0.03115764],
       [0.47953593, 0.5373903 , 0.99972269, 0.45144604, 0.03881305,
        0.85455322, 0.39089372, 0.38233115, 0.3471269 , 0.32292847]])

In [ ]:
new_array=my_array

In [63]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [64]:
a[1,2]

6

In [65]:
a[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
my_array

array([[0.78138219, 0.47664021, 0.98952576, 0.78586048, 0.12498951,
        0.52931984, 0.09080556, 0.19903083, 0.14662074, 0.87930409],
       [0.12401796, 0.89570802, 0.62164808, 0.84320727, 0.84553637,
        0.38317026, 0.2838284 , 0.05423121, 0.19489253, 0.88175782],
       [0.9320304 , 0.26021669, 0.80479284, 0.76822814, 0.10175907,
        0.7729878 , 0.46601094, 0.97447559, 0.84678637, 0.52428617],
       [0.97781464, 0.70358998, 0.17628645, 0.84710726, 0.45328381,
        0.0606557 , 0.75937481, 0.78560602, 0.41007636, 0.31935431],
       [0.36857247, 0.62932669, 0.72415787, 0.98945275, 0.1729777 ,
        0.30101468, 0.59740391, 0.87682127, 0.5987741 , 0.03115764],
       [0.47953593, 0.5373903 , 0.99972269, 0.45144604, 0.03881305,
        0.85455322, 0.39089372, 0.38233115, 0.3471269 , 0.32292847]])

In [74]:
new_array=my_array[:,[1,3,5]]
new_array

array([[0.47664021, 0.78586048, 0.52931984],
       [0.89570802, 0.84320727, 0.38317026],
       [0.26021669, 0.76822814, 0.7729878 ],
       [0.70358998, 0.84710726, 0.0606557 ],
       [0.62932669, 0.98945275, 0.30101468],
       [0.5373903 , 0.45144604, 0.85455322]])

In [75]:
my_array.shape

(6, 10)

In [76]:
new_array.shape

(6, 3)

In [77]:
my_array*new_array

ValueError: operands could not be broadcast together with shapes (6,10) (6,3) 

In [78]:
new_array=new_array.T
new_array.shape

(3, 6)